In [169]:
import requests
import os
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

True

In [170]:
KEY_API_WEATHER = os.environ.get("KEY_API_WEATHER")

In [171]:
response = requests.get(f"https://api.openweathermap.org/data/2.5/weather?q=London&appid={KEY_API_WEATHER}")
data = response.json()
data

{'coord': {'lon': -0.1257, 'lat': 51.5085},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01n'}],
 'base': 'stations',
 'main': {'temp': 275.21,
  'feels_like': 273.69,
  'temp_min': 272.13,
  'temp_max': 277.71,
  'pressure': 1041,
  'humidity': 95},
 'visibility': 10000,
 'wind': {'speed': 1.54, 'deg': 230},
 'clouds': {'all': 0},
 'dt': 1642057172,
 'sys': {'type': 2,
  'id': 2019646,
  'country': 'GB',
  'sunrise': 1642060862,
  'sunset': 1642090607},
 'timezone': 0,
 'id': 2643743,
 'name': 'London',
 'cod': 200}

In [172]:
df_coord = pd.read_csv('assets/top_35_coords_final.csv', index_col=0)
df_coord

           lat                 lon
0   48.6359541  -1.511459954959514
1    48.649518          -2.0260409
2   49.2764624          -0.7024738
3   49.4938975           0.1079732
4   49.4404591           1.0939658
5   48.8588897  2.3200410217200766
6   49.8941708           2.2956951
7   50.6365654           3.0635282
8    48.584614           7.7507127
9   48.2495226           7.3454923
10  48.0777517           7.3579641
11  48.0447968           7.3079618
12  47.2380222           6.0243622
13  47.3215806           5.0414701
14  45.8992348           6.1288847
15  45.7578137           4.8320114
16  45.1875602           5.7357819
17     No data             No data
18  43.1572172   6.329253867921363
19  43.2140359           5.5396318
20  43.2961743           5.3699525
21  43.5298424           5.4474738
22  43.9492493           4.8059012
23  44.0121279           4.4196718
24     No data             No data
25  43.5658225           4.1912837
26  43.4522771           4.4287172
27    42.52505           3.0831554
28  43.2130358           2.3491069
29     No data             No data
30  43.6044622           1.4442469
31  44.0175835           1.3549991
32  43.4832523          -1.5592776
33  43.4933379           -1.475099
34  46.1591126          -1.1520434

In [173]:
cities_coord_lat = []
cities_coord_lon = []
for i, rows in df_coord.iterrows():
    # print(rows)
    cities_coord_lat.append(rows['lat'])
    cities_coord_lon.append(rows['lon'])
display(cities_coord_lat[17])
display(cities_coord_lon[0:10])

'No data'

['-1.511459954959514',
 '-2.0260409',
 '-0.7024738',
 '0.1079732',
 '1.0939658',
 '2.3200410217200766',
 '2.2956951',
 '3.0635282',
 '7.7507127',
 '7.3454923']

In [174]:
def get_meteo(lat, lon):
    k = 0
    for i, j in zip(lat, lon):
        response = requests.get(f"https://api.openweathermap.org/data/2.5/weather?lat={i}&lon={j}&appid={KEY_API_WEATHER}")
        data_coords = response.json()
        print(f"{k}: {data_coords}")
        k += 1
        yield data_coords

top_35_temperature = []
for data in get_meteo(cities_coord_lat, cities_coord_lon):
    # print(data['main']['temp'])
    if  data['cod'] == 400:
        top_35_temperature.append('No data')
    else:
        top_35_temperature.append(data['main']['temp'])

0: {'coord': {'lon': -1.5115, 'lat': 48.636}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'base': 'stations', 'main': {'temp': 276.98, 'feels_like': 274.7, 'temp_min': 276.54, 'temp_max': 279.38, 'pressure': 1040, 'humidity': 89, 'sea_level': 1040, 'grnd_level': 1040}, 'visibility': 10000, 'wind': {'speed': 2.46, 'deg': 90, 'gust': 2.79}, 'clouds': {'all': 10}, 'dt': 1642057349, 'sys': {'type': 1, 'id': 6557, 'country': 'FR', 'sunrise': 1642060480, 'sunset': 1642091655}, 'timezone': 3600, 'id': 6435453, 'name': 'Huisnes-sur-Mer', 'cod': 200}
1: {'coord': {'lon': -2.026, 'lat': 48.6495}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'base': 'stations', 'main': {'temp': 276.86, 'feels_like': 274.46, 'temp_min': 276.44, 'temp_max': 279.27, 'pressure': 1040, 'humidity': 100}, 'visibility': 7000, 'wind': {'speed': 2.57, 'deg': 100}, 'clouds': {'all': 2}, 'dt': 1642057349, 'sys': {'type': 1, 'id': 6557, 'country': 'FR', 'sunrise': 1642060606, 'sunset': 1642091775}, 'timezone': 3600, 'id': 2978640, 'name': 'St-Malo', 'cod': 200}
2: {'coord': {'lon': -0.7025, 'lat': 49.2765}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'base': 'stations', 'main': {'temp': 278.19, 'feels_like': 275.81, 'temp_min': 274.41, 'temp_max': 278.29, 'pressure': 1041, 'humidity': 91, 'sea_level': 1041, 'grnd_level': 1034}, 'visibility': 10000, 'wind': {'speed': 2.86, 'deg': 122, 'gust': 3.98}, 'clouds': {'all': 5}, 'dt': 1642057350, 'sys': {'type': 1, 'id': 6569, 'country': 'FR', 'sunrise': 1642060437, 'sunset': 1642091310}, 'timezone': 3600, 'id': 3034483, 'name': 'Bayeux', 'cod': 200}
3: {'coord': {'lon': 0.108, 'lat': 49.4939}, 'weather': [{'id': 741, 'main': 'Fog', 'description': 'fog', 'icon': '50n'}], 'base': 'stations', 'main': {'temp': 275.3, 'feels_like': 272.16, 'temp_min': 272.87, 'temp_max': 278.54, 'pressure': 1041, 'humidity': 100}, 'visibility': 500, 'wind': {'speed': 3.09, 'deg': 120}, 'clouds': {'all': 100}, 'dt': 1642057576, 'sys': {'type': 1, 'id': 6533, 'country': 'FR', 'sunrise': 1642060294, 'sunset': 1642091063}, 'timezone': 3600, 'id': 3003796, 'name': 'Le Havre', 'cod': 200}
4: {'coord': {'lon': 1.094, 'lat': 49.4405}, 'weather': [{'id': 741, 'main': 'Fog', 'description': 'fog', 'icon': '50n'}], 'base': 'stations', 'main': {'temp': 274.74, 'feels_like': 271.94, 'temp_min': 272.75, 'temp_max': 276.69, 'pressure': 1039, 'humidity': 94}, 'visibility': 350, 'wind': {'speed': 2.57, 'deg': 100}, 'clouds': {'all': 100}, 'dt': 1642057275, 'sys': {'type': 2, 'id': 2006643, 'country': 'FR', 'sunrise': 1642060045, 'sunset': 1642090839}, 'timezone': 3600, 'id': 2982652, 'name': 'Rouen', 'cod': 200}
5: {'coord': {'lon': 2.32, 'lat': 48.8589}, 'weather': [{'id': 741, 'main': 'Fog', 'description': 'fog', 'icon': '50n'}], 'base': 'stations', 'main': {'temp': 275.08, 'feels_like': 275.08, 'temp_min': 274.17, 'temp_max': 276.01, 'pressure': 1041, 'humidity': 98}, 'visibility': 400, 'wind': {'speed': 0.89, 'deg': 45, 'gust': 2.24}, 'clouds': {'all': 100}, 'dt': 1642057350, 'sys': {'type': 2, 'id': 2012208, 'country': 'FR', 'sunrise': 1642059613, 'sunset': 1642090683}, 'timezone': 3600, 'id': 6545270, 'name': 'Palais-Royal', 'cod': 200}
6: {'coord': {'lon': 2.2957, 'lat': 49.8942}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'base': 'stations', 'main': {'temp': 273.35, 'feels_like': 271.58, 'temp_min': 272.66, 'temp_max': 274.59, 'pressure': 1041, 'humidity': 84, 'sea_level': 1041, 'grnd_level': 1037}, 'visibility': 10000, 'wind': {'speed': 1.53, 'deg': 69, 'gust': 1.51}, 'clouds': {'all': 0}, 'dt': 1642057350, 'sys': {'type': 2, 'id': 2011713, 'country': 'FR', 'sunrise': 1642059867, 'sunset': 1642090440}, 'timezone': 3600, 'id': 3037854, 'name': 'Amiens', 'cod': 200}
7: {'coord': {'lon': 3.0635, 'lat': 50.6366}, 'weather': [{'id': 741, 'main': 'Fog', 'description': 'fog', 'icon': '50n'}], 'base': 'stations', 'main': {'temp': 273.65, 'feels_like': 271.9, 'temp_min': 272.97, 'temp_max': 274.21, 'pressure': 1040, 'humidity': 89}, 'visibility': 500, 'wind': {'speed': 1.54, 'deg': 0}, 'clouds': {'all': 100}, 'dt': 1642057350, 'sys': {'type': 2, 'id': 2011132, 'country': 'FR', 'sunrise': 1642059869, 'sunset': 1642090069}, 'timezone': 3600, 'id': 2998324, 'name': 'Lille', 'cod': 200}
8: {'coord': {'lon': 7.7507, 'lat': 48.5846}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'base': 'stations', 'main': {'temp': 269.36, 'feels_like': 266.2, 'temp_min': 266.97, 'temp_max': 270.91, 'pressure': 1041, 'humidity': 93}, 'visibility': 7000, 'wind': {'speed': 2.06, 'deg': 360}, 'clouds': {'all': 2}, 'dt': 1642057350, 'sys': {'type': 1, 'id': 6595, 'country': 'FR', 'sunrise': 1642058246, 'sunset': 1642089442}, 'timezone': 3600, 'id': 2973783, 'name': 'Strasbourg', 'cod': 200}
9: {'coord': {'lon': 7.3455, 'lat': 48.2495}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'base': 'stations', 'main': {'temp': 265.27, 'feels_like': 265.27, 'temp_min': 264.05, 'temp_max': 267.58, 'pressure': 1040, 'humidity': 93}, 'visibility': 10000, 'wind': {'speed': 1.03, 'deg': 310}, 'clouds': {'all': 0}, 'dt': 1642057351, 'sys': {'type': 1, 'id': 6482, 'country': 'FR', 'sunrise': 1642058266, 'sunset': 1642089616}, 'timezone': 3600, 'id': 6441605, 'name': 'Saint-Hippolyte', 'cod': 200}
10: {'coord': {'lon': 7.358, 'lat': 48.0778}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'base': 'stations', 'main': {'temp': 268.42, 'feels_like': 268.42, 'temp_min': 267.09, 'temp_max': 270.06, 'pressure': 1040, 'humidity': 93}, 'visibility': 10000, 'wind': {'speed': 1.03, 'deg': 310}, 'clouds': {'all': 0}, 'dt': 1642057351, 'sys': {'type': 1, 'id': 6482, 'country': 'FR', 'sunrise': 1642058224, 'sunset': 1642089652}, 'timezone': 3600, 'id': 3024297, 'name': 'Colmar', 'cod': 200}
11: {'coord': {'lon': 7.308, 'lat': 48.0448}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'base': 'stations', 'main': {'temp': 268.38, 'feels_like': 268.38, 'temp_min': 267.05, 'temp_max': 270.03, 'pressure': 1040, 'humidity': 93}, 'visibility': 10000, 'wind': {'speed': 1.03, 'deg': 310}, 'clouds': {'all': 0}, 'dt': 1642057351, 'sys': {'type': 1, 'id': 6482, 'country': 'FR', 'sunrise': 1642058229, 'sunset': 1642089671}, 'timezone': 3600, 'id': 3020324, 'name': 'Eguisheim', 'cod': 200}
12: {'coord': {'lon': 6.0244, 'lat': 47.238}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'base': 'stations', 'main': {'temp': 269.92, 'feels_like': 266.74, 'temp_min': 266.24, 'temp_max': 274.17, 'pressure': 1038, 'humidity': 59, 'sea_level': 1038, 'grnd_level': 1006}, 'visibility': 10000, 'wind': {'speed': 2.14, 'deg': 74, 'gust': 4.92}, 'clouds': {'all': 0}, 'dt': 1642057351, 'sys': {'type': 2, 'id': 2008637, 'country': 'FR', 'sunrise': 1642058358, 'sunset': 1642090158}, 'timezone': 3600, 'id': 3033123, 'name': 'Besançon', 'cod': 200}
13: {'coord': {'lon': 5.0415, 'lat': 47.3216}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'base': 'stations', 'main': {'temp': 270.79, 'feels_like': 266.28, 'temp_min': 267.79, 'temp_max': 272.16, 'pressure': 1038, 'humidity': 80}, 'visibility': 9000, 'wind': {'speed': 3.6, 'deg': 360}, 'clouds': {'all': 0}, 'dt': 1642057351, 'sys': {'type': 1, 'id': 6586, 'country': 'FR', 'sunrise': 1642058612, 'sunset': 1642090376}, 'timezone': 3600, 'id': 3006622, 'name': 'Larrey', 'cod': 200}
14: {'coord': {'lon': 6.1289, 'lat': 45.8992}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'base': 'stations', 'main': {'temp': 269.15, 'feels_like': 269.15, 'temp_min': 267.79, 'temp_max': 271.96, 'pressure': 1036, 'humidity': 93}, 'visibility': 6000, 'wind': {'speed': 0, 'deg': 0}, 'clouds': {'all': 75}, 'dt': 1642057351, 'sys': {'type': 1, 'id': 6500, 'country': 'FR', 'sunrise': 1642058050, 'sunset': 1642090416}, 'timezone': 3600, 'id': 3037543, 'name': 'Annecy', 'cod': 200}
15: {'coord': {'lon': 4.832, 'lat': 45.7578}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'base': 'stations', 'main': {'temp': 271.09, 'feels_like': 267.09, 'temp_min': 269.39, 'temp_max': 273.01, 'pressure': 1037, 'humidity': 86}, 'visibility': 7000, 'wind': {'speed': 3.09, 'deg': 330}, 'clouds': {'all': 100}, 'dt': 1642057351, 'sys': {'type': 1, 'id': 6505, 'country': 'FR', 'sunrise': 1642058333, 'sunset': 1642090756}, 'timezone': 3600, 'id': 8015556, 'name': 'Vieux Lyon', 'cod': 200}
16: {'coord': {'lon': 5.7358, 'lat': 45.1876}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'base': 'stations', 'main': {'temp': 271.19, 'feels_like': 271.19, 'temp_min': 269.25, 'temp_max': 272.21, 'pressure': 1038, 'humidity': 91}, 'visibility': 10000, 'wind': {'speed': 0.89, 'deg': 219, 'gust': 2.68}, 'clouds': {'all': 0}, 'dt': 1642057352, 'sys': {'type': 2, 'id': 2004515, 'country': 'FR', 'sunrise': 1642058001, 'sunset': 1642090654}, 'timezone': 3600, 'id': 6454071, 'name': 'Grenoble', 'cod': 200}
17: {'cod': '400', 'message': 'wrong latitude'}

KeyError: 'main'

In [180]:
top_35_temperature_final = pd.DataFrame(top_35_temperature)
top_35_temperature_final.columns =['temp_K']
top_35_temperature_final

    temp_K
0   276.98
1   276.86
2   278.19
3   275.30
4   274.74
5   275.08
6   273.35
7   273.65
8   269.36
9   265.27
10  268.42
11  268.38
12  269.92
13  270.79
14  269.15
15  271.09
16  271.19

In [181]:
top_35_temperature_final.to_csv('assets/top_35_temperature.csv')