In [4]:
import pandas as pd
import requests

In [5]:
df = pd.read_csv('assets/top_35_clean.csv', index_col=0)
df.head(40)

                           Cities
0               Mont Saint Michel
1                         St Malo
2                          Bayeux
3                        Le Havre
4                           Rouen
5                           Paris
6                          Amiens
7                           Lille
8                      Strasbourg
9    Chateau du Haut Koenigsbourg
10                         Colmar
11                      Eguisheim
12                       Besancon
13                          Dijon
14                         Annecy
15                           Lyon
16                       Grenoble
17                   Verdon Gorge
18             Bormes les Mimosas
19                         Cassis
20                      Marseille
21                Aix en Provence
22                       Avignon
23                           Uzès
24                         Nimmes
25                  Aigues Mortes
26       Saintes Maries de la Mer
27                      Collioure
28                    Carcassonne
29                         Ariege
30                       Toulouse
31                      Montauban
32                       Biarritz
33                        Bayonne
34                    La Rochelle

In [6]:
response = requests.get("https://nominatim.openstreetmap.org/")
response

In [7]:
cities_list = []
for i, rows in df.iterrows():
    cities_list.append(rows[0])
cities_list

[' Mont Saint Michel',
 ' St Malo',
 ' Bayeux',
 ' Le Havre',
 ' Rouen',
 ' Paris',
 ' Amiens',
 ' Lille',
 ' Strasbourg',
 ' Chateau du Haut Koenigsbourg',
 ' Colmar',
 ' Eguisheim',
 ' Besancon',
 ' Dijon',
 ' Annecy',
 ' Lyon',
 ' Grenoble',
 ' Verdon Gorge',
 ' Bormes les Mimosas',
 ' Cassis',
 ' Marseille',
 ' Aix en Provence',
 ' Avignon ',
 ' Uzès',
 ' Nimmes',
 ' Aigues Mortes',
 ' Saintes Maries de la Mer',
 ' Collioure',
 ' Carcassonne',
 ' Ariege',
 ' Toulouse',
 ' Montauban',
 ' Biarritz',
 ' Bayonne',
 ' La Rochelle']

In [8]:
def get_coordinates(input_list):
    for city in input_list:
        gps = requests.get(f"https://nominatim.openstreetmap.org/search?city={city}&format=json&limit=1")
        data = gps.json()
        yield data

In [9]:
get_coordinates(cities_list)

In [17]:
top_35_coords_lat = []
top_35_coords_lon = []
for data in get_coordinates(cities_list):
    if data ==[]:
        # print('No data')
        top_35_coords_lat.append('No data')
        top_35_coords_lon.append('No data')
    else:
        # print(data[0]['lat'], data[0]['lon'])
        top_35_coords_lat.append(data[0]['lat'])
        top_35_coords_lon.append(data[0]['lon'])

In [27]:
top_35_coords_final = pd.DataFrame([top_35_coords_lat, top_35_coords_lon], index=['lat', 'lon']).T
top_35_coords_final.head()

          lat                 lon
0  48.6359541  -1.511459954959514
1   48.649518          -2.0260409
2  49.2764624          -0.7024738
3  49.4938975           0.1079732
4  49.4404591           1.0939658

In [25]:
top_35_coords_final.to_csv('assets/top_35_coords_final.csv')