In [39]:
import pandas as pd
import boto3

### IMPORT

In [32]:
df_cities = pd.read_csv('assets/top_35_clean.csv', index_col=0)
df_coords = pd.read_csv('assets/top_35_coords_final.csv', index_col=0)
df_temp = pd.read_csv('assets/top_35_temperature.csv', index_col=0)

In [33]:
df_cities.head(1)

               Cities
0   Mont Saint Michel

In [34]:
df_coords.head()

          lat                 lon
0  48.6359541  -1.511459954959514
1   48.649518          -2.0260409
2  49.2764624          -0.7024738
3  49.4938975           0.1079732
4  49.4404591           1.0939658

In [35]:
df_temp.head()

   temp_K
0  276.98
1  276.86
2  278.19
3  275.30
4  274.74

### JOIN

In [36]:
df_cities_coords = pd.merge(df_cities, df_coords, left_index=True, right_index=True)
df_cities_coords_temp = pd.merge(df_cities_coords, df_temp, left_index=True, right_index=True)
df_cities_coords_temp

                           Cities         lat                 lon  temp_K
0               Mont Saint Michel  48.6359541  -1.511459954959514  276.98
1                         St Malo   48.649518          -2.0260409  276.86
2                          Bayeux  49.2764624          -0.7024738  278.19
3                        Le Havre  49.4938975           0.1079732  275.30
4                           Rouen  49.4404591           1.0939658  274.74
5                           Paris  48.8588897  2.3200410217200766  275.08
6                          Amiens  49.8941708           2.2956951  273.35
7                           Lille  50.6365654           3.0635282  273.65
8                      Strasbourg   48.584614           7.7507127  269.36
9    Chateau du Haut Koenigsbourg  48.2495226           7.3454923  265.27
10                         Colmar  48.0777517           7.3579641  268.42
11                      Eguisheim  48.0447968           7.3079618  268.38
12                       Besancon  47.2380222           6.0243622  269.92
13                          Dijon  47.3215806           5.0414701  270.79
14                         Annecy  45.8992348           6.1288847  269.15
15                           Lyon  45.7578137           4.8320114  271.09
16                       Grenoble  45.1875602           5.7357819  271.19

In [37]:
# A custom IQR function
def celsious(column):
    return column + (-273)
    
# Print IQR of the temperature_c column
df_cities_coords_temp['temp_C']= df_cities_coords_temp['temp_K'].agg(celsious)

In [38]:
df_cities_coords_temp

,Cities,lat,lon,temp_K,temp_C
0,Mont Saint Michel,48.6359541,-1.511459954959514,276.98,3.98
1,St Malo,48.649518,-2.0260409,276.86,3.86
2,Bayeux,49.2764624,-0.7024738,278.19,5.19
3,Le Havre,49.4938975,0.1079732,275.30,2.30
4,Rouen,49.4404591,1.0939658,274.74,1.74
5,Paris,48.8588897,2.3200410217200766,275.08,2.08
6,Amiens,49.8941708,2.2956951,273.35,0.35
7,Lille,50.6365654,3.0635282,273.65,0.65
8,Strasbourg,48.584614,7.7507127,269.36,-3.64
9,Chateau du Haut Koenigsbourg,48.2495226,7.3454923,265.27,-7.73
10,Colmar,48.0777517,7.3579641,268.42,-4.58
11,Eguisheim,48.0447968,7.3079618,268.38,-4.62
12,Besancon,47.2380222,6.0243622,269.92,-3.08
13,Dijon,47.3215806,5.0414701,270.79,-2.21
14,Annecy,45.8992348,6.1288847,269.15,-3.85
15,Lyon,45.7578137,4.8320114,271.09,-1.91
16,Grenoble,45.1875602,5.7357819,271.19,-1.81

### AWS

In [40]:
# Generate the boto3 client for interacting with S3
s3 = boto3.client('s3', region_name='us-east-1', 
                        # Set up AWS credentials 
                        aws_access_key_id=AWS_KEY_ID, 
                         aws_secret_access_key=AWS_SECRET)
# List the buckets
buckets = s3.list_buckets()

# Print the buckets
print(buckets)

NameError: name 'AWS_KEY_ID' is not defined